### ISSUE TITLE
Crashing when entering a dimension with a skill lock

### ISSUE THREAD

**Issue by 8BrickDMG** [Coders-After-Dark/CompatSkills#70] opened 2018-06-14 20:22 UTC
The crash occurred when I was moving from the Overworld to the Nether. The Nether portal has a skill requirement attached to it. When you go through the portal and come out the other side, the client crashes and vice versa. 

Restarting and entering the world puts you back into the dimension you intended on visiting.

Please find my crash report attached.

Compatskills v1.8.0
Reskillable v1.7.1
[crash-2018-06-14_21.12.14-server.txt](https://github.com/Coders-After-Dark/CompatSkills/files/2103877/crash-2018-06-14_21.12.14-server.txt)

**Comment by pupnewfster** [comment] 2018-06-14 20:55
Can you provide me with the script you are using. I am unable to reproduce it just by having a lock on the dimension. Also is this crash in single player or multiplayer.

**Comment by pupnewfster** [comment] 2018-06-17 23:37
I believe that this is the same issue as https://github.com/Coders-After-Dark/Reskillable/issues/125 which I will look into as I believe this missing information from here was that it is on a server.

**Comment by whitestarx0312** [comment] 2018-06-18 06:09
Yes and mine isn't due to dimensional travel because I didn't lock any of the portals, but mine does crash upon left/right click, which I assume is because I locked an advancement to right click a block. I'll post my script on my issue

**Comment by pupnewfster** [comment] 2018-06-18 19:24
Should be fixed by https://github.com/Coders-After-Dark/Reskillable/commit/bac7df5907cad9f555a352a24f459bb492fad45c

**Closed by pupnewfster** 2018-06-18 19:24 UTC
